# Generated by Django 3.2.12 on 2022-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipments', 'IT Equipments'), ('Cosmetics', 'Cosmetics'), ('Snacks', 'Snacks'), ('Stationary', 'Stationary'), ('Medical', 'Medical'), ('Electronics', 'Electronics')], max_length=50, null=True),
        ),
    ]
